








source 'http://rubygems.org'
 
ruby '2.2.0'
gem 'padrino'

group :test do
  gem 'minitest', '~> 5.4'
  gem 'nokogiri'
  gem 'to_regexp'
  gem 'mongo'
  gem 'mechanize'
  gem 'levenshtein'
  gem 'bson'
  gem 'bson_ext'
  gem 'rerun'
end

